import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.InputMap;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GO_internet
 */
public class TitleMain extends javax.swing.JFrame {

    /**
     * Creates new form TitleMain
     */Timer timer;
     Clip titlemain;
     Clip buttonclick;
     
    public TitleMain() {
       
        initComponents();
         this.setTitle("CODED");
        this.setLocationRelativeTo(null);
        playMain();
        
        //addBindings();   
    }
    public void playMain() {
        try{
            AudioInputStream audioIn=AudioSystem.getAudioInputStream(
               TitleMain.class.getResource("main.wav"));
            titlemain=AudioSystem.getClip();
            titlemain.open(audioIn);
            titlemain.start();
          
                }
        catch(Exception e){
            System.out.print(e);
        }
    
    }
    //public void addBindings(){
        
        
   // }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        leaderBoard = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(41, 41, 41));
        setPreferredSize(new java.awt.Dimension(400, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jean M Costillas\\Documents\\gwy\\cs 4\\play2.png")); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 200, 170));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playhowto.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 106, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("X");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 50, -1));

        leaderBoard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jean M Costillas\\Documents\\gwy\\cs 4\\NETBEANS\\star.png")); // NOI18N
        leaderBoard.setContentAreaFilled(false);
        leaderBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBoardActionPerformed(evt);
            }
        });
        getContentPane().add(leaderBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 10));

        jLabel2.setBackground(new java.awt.Color(41, 41, 41));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jean M Costillas\\Documents\\gwy\\cs 4\\title.gif")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 700, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        try{
            AudioInputStream audioIn=AudioSystem.getAudioInputStream(
               TitleMain.class.getResource("buttonclick.wav"));
            buttonclick=AudioSystem.getClip();
            buttonclick.open(audioIn);
            buttonclick.start();
          
                }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainTwo main = new MainTwo();
        main.setVisible(true);
        titlemain.stop();
        
        try{
            AudioInputStream audioIn=AudioSystem.getAudioInputStream(
               TitleMain.class.getResource("buttonclick.wav"));
            buttonclick=AudioSystem.getClip();
            buttonclick.open(audioIn);
            buttonclick.start();
          
                }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void leaderBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBoardActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LeaderBoard lboard = new LeaderBoard();
        lboard.setVisible(true);
        try{
            AudioInputStream audioIn=AudioSystem.getAudioInputStream(
               TitleMain.class.getResource("buttonclick.wav"));
            buttonclick=AudioSystem.getClip();
            buttonclick.open(audioIn);
            buttonclick.start();
          
                }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_leaderBoardActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        HOW how = new HOW();
        how.setVisible(true);
        try{
            AudioInputStream audioIn=AudioSystem.getAudioInputStream(
               TitleMain.class.getResource("buttonclick.wav"));
            buttonclick=AudioSystem.getClip();
            buttonclick.open(audioIn);
            buttonclick.start();
          
                }
        catch(Exception e){
            System.out.print(e);
        }
        titlemain.stop();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton leaderBoard;
    // End of variables declaration//GEN-END:variables
}
